### ISSUE TITLE
appfs/nodejs/img-resize hangs when running on snapfaas from kernel

### ISSUE THREAD

**Issue by tan-yue** [princeton-sns/snapfaas-images#2]
```bash
sudo target/release/fc_wrapper \
--kernel_args 'console=ttyS0' \
--kernel resources/images/vmlinux-4.20.0 \
--rootfs resources/images/runtimefs/nodejs.ext4 \
--appfs snapfaas-images/appfs/nodejs/img-resize/output.ext2 \
--mem_size 128 \
--vcpu_count 1 \
--network 'tap0/aa:bb:cc:dd:ff:ff'  < resources/requests/img-resize-nodejs.json
```
The above command hangs after the guest connects to the host.

However, Inside `.img-resize`, `make test` can complete.
And `ocr` + `lorem` running on snapfaas can complete too.

**Comment by tan-yue** [comment]
I've moved `img-resize` to `.img-resize` such that microbenchmark can idiomatically skip apps.

**Comment by tan-yue** [comment]
`.alexa-fact` also hangs after the guest connects to the host.

**Comment by alevy** [comment]
There are three problems with `.img-resize` (all fixed in #3):

  1. It needs more disk space to actually compile an image. I gave it 50MB.

  2. It needs more than 128MB of memory to run. 256MB works, though it seems to be right on the edge, as small changes to the code (e.g. removing a `setTimeout` somewhere in the Jimp library) made it work for me in many cases (presumably because there was one or two fewer heap allocations).

  2. The vsock library itself was buggy as detailed in #3: basically for multiple requests with large responses (e.g. img-resize), it would end up remaining blocked in the second `readRequest` before the previous `writeRequest` had finished writing all data to the vsock, so SnapFaas wouldn't consider the first request complete.

**Comment by alevy** [comment]
Note that the `.alex-*` apps require porting with the new interface I introduced in #3. It's trivial to port, but I wasn't sure if those apps were actually supposed to be working.

**Comment by tan-yue** [comment]
I'll look into making `.alexa-*` apps work. I ported them such that `make test` can successfully complete.

**Comment by tan-yue** [comment]
> 2. It needs more than 128MB of memory to run. 256MB works, though it seems to be right on the edge, as small changes to the code (e.g. removing a `setTimeout` somewhere in the Jimp library) made it work for me in many cases (presumably because there was one or two fewer heap allocations).

I updated img-resize/image.js to make it runnable using just 128MB memory
